/**
 * After `astro build`:
 *   1. Hash every inline <script> and <style> so the CSP needs no
 *      'unsafe-inline'. Astro inlines the stylesheet, so this is the only way
 *      to keep both a strict policy and zero render-blocking requests.
 *   2. Write dist/_headers (security + caching).
 *   3. Report page weight against the budget in CLAUDE.md section 9.
 */
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';
import { gzipSync } from 'node:zlib';

const DIST = 'dist';

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(path)));
    else out.push(path);
  }
  return out;
}

const files = await walk(DIST);
const pages = files.filter((f) => f.endsWith('.html'));

const scriptHashes = new Set();
const styleHashes = new Set();
const sha = (s) => `'sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}'`;

for (const page of pages) {
  const html = await readFile(page, 'utf8');
  for (const m of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
    if (m[1].length) scriptHashes.add(sha(m[1]));
  }
  for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)) {
    if (m[1].length) styleHashes.add(sha(m[1]));
  }
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...scriptHashes].join(' ')}`,
  `style-src 'self' ${[...styleHashes].join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  "manifest-src 'self'",
  'upgrade-insecure-requests',
].join('; ');

// Cloudflare Pages APPENDS the values of every matching _headers rule rather
// than letting a more specific one win. A Cache-Control on /* therefore leaks
// into /fonts/* and /_astro/*, producing
//   "public, max-age=0, must-revalidate, public, max-age=31536000, immutable"
// which is ambiguous and cost the long-lived assets their caching. So /* carries
// security headers only, and Cache-Control is set per path, without overlap.
const htmlRoutes = pages
  .map((p) => '/' + relative(DIST, p).split('\\').join('/').replace(/(^|\/)index\.html$/, '$1').replace(/\.html$/, ''))
  .sort();

const headers = `# Generated by scripts/postbuild.mjs — do not edit by hand.
# The CSP carries a hash for every inline <script> and <style> the build
# emitted, so no 'unsafe-inline' is needed anywhere.
#
# Note: Pages appends matching rules, it does not override them. Nothing below
# may set Cache-Control on a path that another rule also matches.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY

# Hashed filenames: safe to cache forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Subset fonts, content-stable filenames.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# HTML: always revalidate, so an edit is live immediately.
${htmlRoutes.map((r) => `${r}\n  Cache-Control: public, max-age=0, must-revalidate`).join('\n')}

# Generated brand assets: stable, but not content-hashed.
${['/favicon.svg', '/favicon-32.png', '/apple-touch-icon-180.png', '/icon-192.png', '/icon-512.png', '/og.png']
  .map((r) => `${r}\n  Cache-Control: public, max-age=604800`).join('\n')}
/manifest.webmanifest
  Cache-Control: public, max-age=86400
`;

await writeFile(join(DIST, '_headers'), headers);

// Without this, the Functions worker is invoked for every request and the
// static asset server's 404.html handling is bypassed — unknown URLs come back
// as the home page with a 200, which is a soft 404 and indexable.
await writeFile(
  join(DIST, '_routes.json'),
  JSON.stringify({ version: 1, include: ['/api/*'], exclude: [] }, null, 2) + '\n',
);

// ---- budget report --------------------------------------------------------
// Counts the HTML plus everything it references that is not a lazy image.
const sizeOf = async (f) => (await stat(f)).size;
const gz = async (f) => gzipSync(await readFile(f)).length;

const shared = [];
for (const f of files) {
  const rel = '/' + relative(DIST, f).split('\\').join('/');
  if (rel.startsWith('/fonts/') && rel.endsWith('.woff2')) shared.push([rel, await gz(f)]);
}
const fontsTotal = shared.reduce((a, [, n]) => a + n, 0);

console.log('\n  page                     html(gz)   +fonts   budget');
console.log('  ' + '-'.repeat(52));
let worst = 0;
for (const page of pages.sort()) {
  const rel = '/' + relative(DIST, page).split('\\').join('/');
  const h = await gz(page);
  const total = h + fontsTotal;
  worst = Math.max(worst, total);
  const budget = rel === '/index.html' ? 450 : 300;
  const ok = total / 1024 < budget ? 'ok' : 'OVER';
  console.log(
    `  ${rel.padEnd(24)} ${(h / 1024).toFixed(1).padStart(6)}K ${(total / 1024).toFixed(1).padStart(8)}K   ${budget}K ${ok}`,
  );
}

const cssBytes = (await Promise.all(pages.map(async (p) => {
  const html = await readFile(p, 'utf8');
  return [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].reduce((a, m) => a + m[1].length, 0);
}))).reduce((a, b) => Math.max(a, b), 0);

const jsBytes = (await Promise.all(pages.map(async (p) => {
  const html = await readFile(p, 'utf8');
  return [...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)].reduce((a, m) => a + m[1].length, 0);
}))).reduce((a, b) => Math.max(a, b), 0);

const external = files.filter((f) => f.includes('_astro') && f.endsWith('.js'));
const extJs = (await Promise.all(external.map(gz))).reduce((a, b) => a + b, 0);

console.log('');
console.log(`  inline CSS (largest page, raw)  ${(cssBytes / 1024).toFixed(1)}K   budget 40K`);
console.log(`  JS (largest page inline + bundles, raw/gz)  ${(jsBytes / 1024).toFixed(1)}K + ${(extJs / 1024).toFixed(1)}K   budget 60K`);
console.log(`  fonts  ${shared.length} woff2 files, ${(fontsTotal / 1024).toFixed(1)}K gz   budget 4 files / 120K`);
console.log(`  CSP: ${scriptHashes.size} script hashes, ${styleHashes.size} style hashes\n`);
